[phases.setup]
nixPkgs = ["python310", "gcc", "g++"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements-railway.txt"]

[start]
cmd = "chmod +x start.sh && ./start.sh"
